name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'review-2')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: project-files
          # The artifact is downloaded from the workflow run that triggered this workflow
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Copy compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            docker-compose.yandex.yml
            nginx/nginx.prod.conf
          target: "~/film-react-nest"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим в директорию с проектом на сервере
            cd ~/film-react-nest

            # Экспортируем переменные окружения для docker-compose
            export IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
            export YC_REGISTRY_ID=${{ secrets.YC_REGISTRY_ID }}
            
            # Логинимся в Yandex Container Registry на сервере
            echo '${{ secrets.YC_SA_KEY_JSON }}' | docker login --username json_key --password-stdin cr.yandex
            
            # Загружаем актуальные образы
            docker compose -f docker-compose.yandex.yml pull
            
            # Перезапускаем сервисы с новыми образами
            docker compose -f docker-compose.yandex.yml up -d --remove-orphans
            
            # Очищаем старые, неиспользуемые образы
            docker image prune -f
