name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'review-2'
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        uses: okar1/yc-cli-install@master
        with:
          SA_KEY: ${{ secrets.YC_SA_KEY_JSON }}

      - name: Get VM external IP
        id: vm
        run: |
          VM_NAME="film-nest-vm"
          EXTERNAL_IP=$(yc compute instance get "$VM_NAME" --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')
          if [ -z "$EXTERNAL_IP" ]; then
            echo "::error::VM not found or has no external IP. Please run the 'Provision Infrastructure' workflow first."
            exit 1
          fi
          echo "external_ip=$EXTERNAL_IP" >> "$GITHUB_OUTPUT"

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Copy .env to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ steps.vm.outputs.external_ip }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: "/home/${{ secrets.SSH_USERNAME }}/film-nest-prod"

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.vm.outputs.external_ip }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SSH_USERNAME }}/film-nest-prod
            
            # Логинимся в Yandex Container Registry
            echo '${{ secrets.YC_SA_KEY_JSON }}' | docker login --username json_key --password-stdin cr.yandex
            
            # Обновляем код из репозитория
            git pull origin review-2
            
            # Запускаем сервисы с новыми образами
            IMAGE_TAG=${{ github.sha }} docker compose -f docker-compose.yandex.yml up -d --remove-orphans
            
            # Перезапускаем Nginx для надежности
            docker compose restart nginx
            
            # Чистим старые образы
            docker image prune -a -f --filter "until=24h"
