name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Запускаем деплой для веток main и review-2, если CI прошел успешно
    if: >
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'review-2') &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker tag
        id: vars
        run: |
          # Используем имя ветки для тега, 'latest' для main
          branch_name=${{ github.event.workflow_run.head_branch }}
          if [ "$branch_name" == "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo ${branch_name} | sed -e 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_OUTPUT
          fi

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY_JSON }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/film-react-nest-backend:${{ steps.vars.outputs.tag }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile.frontend.prod
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/film-react-nest-nginx:${{ steps.vars.outputs.tag }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Выход при любой ошибке
            set -e
            # Переходим в директорию проекта
            cd ~/film-react-nest
            # Загружаем последние изменения из репозитория (например, обновления docker-compose.yml)
            git pull origin ${{ github.event.workflow_run.head_branch }}
            # Экспортируем переменные для docker-compose
            # Тэг образа, соответствующий ветке
            export IMAGE_TAG=${{ steps.vars.outputs.tag }}
            # ID реестра, чтобы docker-compose мог составить полный путь к образу
            export YC_REGISTRY_ID=${{ secrets.YC_REGISTRY_ID }}
            
            # Получаем временный IAM-токен для привязанного к ВМ сервисного аккаунта
            # и логинимся в Yandex Container Registry.
            # Эта команда выполняется при каждом деплое для безопасности.
            /home/ubuntu/yandex-cloud/bin/yc container registry get-login | docker login --username iam --password-stdin cr.yandex
            
            # Аутентификация Docker уже настроена на сервере с помощью 'yc configure-docker',
            # поэтому дополнительный вход не требуется.
            # Загружаем актуальные образы
            docker-compose -f docker-compose.yandex.yml --env-file ./.env pull
            # Перезапускаем сервисы с новыми образами
            docker-compose -f docker-compose.yandex.yml --env-file ./.env up -d
            # Очищаем старые неиспользуемые образы, чтобы не занимать место
            docker image prune -f
