name: CI Pipeline

on:
  push:
    branches: [ main, review-2 ]
  pull_request:
    branches: [ main, review-2 ]

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install frontend dependencies
      run: pnpm --dir ./frontend install

    - name: Run linter
      run: pnpm --dir ./frontend lint

    - name: Build frontend
      run: pnpm --dir ./frontend build

  test_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'pnpm'
        cache-dependency-path: backend/pnpm-lock.yaml

    - name: Install backend dependencies
      run: pnpm --dir ./backend install

    - name: Run linter
      run: pnpm --dir ./backend lint

    - name: Run backend tests
      run: pnpm --dir ./backend test

    - name: Build backend
      run: pnpm --dir ./backend build
