name: CI

on:
  push:
    branches: [ main, review-2 ]
  pull_request:
    branches: [ main, review-2 ]

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'pnpm'
        cache-dependency-path: frontend/pnpm-lock.yaml # Указываем путь к lock-файлу фронтенда

    - name: Install frontend dependencies
      run: pnpm --dir ./frontend install --frozen-lockfile

    - name: Build frontend
      run: pnpm --dir ./frontend build

  test_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'pnpm'
        cache-dependency-path: backend/pnpm-lock.yaml # Указываем путь к lock-файлу бэкенда

    - name: Install backend dependencies
      run: pnpm --dir ./backend install --frozen-lockfile

    - name: Run backend tests
      run: pnpm --dir ./backend test

    - name: Build backend
      run: pnpm --dir ./backend build
